
name: Deploy On Server

env:
  DOTNET_VERSION: '5.0.x'                 # set this to the .NET Core version to use
  DOTNET_ROOT: './'
  APP_NAME: 'LinuxApp.Api'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy files via scp
        uses: appleboy/scp-action@master              
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: ${{env.DOTNET_ROOT}}
          target: ${{ secrets.COPY_TO }}

      - name: Move files to temp folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: rm -rf ${{ secrets.COPY_LAST }};mv ${{ secrets.COPY_FROM }} ${{ secrets.COPY_LAST }};cd ${{ secrets.COPY_LAST }};

      - name: Build and publish app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: rm -rf app/;cd ${{ secrets.COPY_LAST }};dotnet build -c Release -o ~/app;dotnet publish -c Release -o ~/app;

      - name: Move files to deployment folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: sudo rm -rf ${{ secrets.APP_LOCATION }};sudo mv app/ ${{ secrets.APP_LOCATION }}; sudo systemctl reload nginx;
        
